# Generated by Django 5.1.3 on 2024-11-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='user',
        ),
    ]
